# Generated by Django 6.0 on 2025-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('bar', 'Бар'), ('park', 'Парк'), ('cinema', 'Кінотеатр'), ('club', 'Клуб'), ('other', 'Інше')], max_length=20, verbose_name='Тип місця'),
        ),
    ]
